# Site settings
title: *folio
email: chipohao@zonesoundcreative.com
description: > # this means to ignore newlines until "baseurl:"
  An online portfolio from artsit and musician CHI PO-HAO.
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: @stu84096
github_username:  chipohao@mit.edu

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/


